sudo: false
language: python
python:
  - "3.6"

install:
  - pip install tox
script:
  - tox

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=black
  - python: 3.6
    env: TOXENV=pylint
